### ISSUE TITLE
[REQUEST] V1/VR/V2 speed calculation

### ISSUE THREAD

**Issue by KyleCyaN** [flybywiresim/aircraft#3393]
**V1/VR/V2 speed calculation error**

The calculation of the V1/VR/V2 speed on the PERF page on the MCDU does not include the calculation of fuel data, so the calculation of the V1/VR/V2 speed is unreasonable.The calculation of the V1/VR/V2 speed on the PERF page on the MCDU does not include the calculation of fuel data, so the calculation of the V1/VR/V2 speed is unreasonable. The data used for calculation should include a variety of necessary or possible factors, such as wind direction, wind speed, air pressure, aircraft load, fuel quantity and so on.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
This is already being worked on https://github.com/flybywiresim/a32nx/pull/3350

**Comment by donstim** [comment]
The current V1?VR/V2 values do include the consideration of how much fuel is on board. These speeds are a function of the airplane weight, which includes empty weight, fuel on board, and payload. The speeds are entirely reasonable and match real life values.

The current V2 speeds include consideration of all the factors that go into calculation of V2 speeds. They are within a knot or 2 of real life values throughout the takeoff envelope. There is very little variation of takeoff speed with pressure altitude, but it is there (1 knot per 5000 feet for CONF 3). VR and V1 speeds are simplified, but they are also within a few knots of the actual speeds throughout the envelope. At higher temperatures and higher elevation airports. V1 and VR may be a bit less than shown.

Takeoff speeds are airspeeds and are are unaffected by wind direction and wind speed.

I recommend closing this issue, both on procedural grounds (the "BY REMOVING THIS LINE" line was not removed) and technical grounds because the claims made it in are both false and not supported by any factual reference information.

**Comment by CyaN13247** [comment]
I'm understood, thank you for your explanation.

donstim <notifications@github.com>于2021年2月8日 周一上午1:43写道：

**Comment by GlitchedYT** [comment]
Not gonna lie, but they dont "seem" very realistic. every time i input vspeeds into the mcdu i get i.e. V1 134, VR 135, V2 141. It seems like whatever i get for V1, VR is always +1 and V2 is always VR +4. It just doesn't seem like thats correct. For example, in the fslabs, the v speeds are always different, sometimes v1 and vr could be the same sometimes they are 10 knots apart. Just my two cents though.

**Comment by CyaN13247** [comment]
Indeed, it is reasonable to say that when I use MCDU to calculate these
three speeds, most of the time it is V1 121, VR 122, V2 126.That's why I
wonder if these three speeds are miscalculated ...🙂🙂🙂

GlitchedYT <notifications@github.com>于2021年2月8日 周一上午2:03写道：

**Comment by donstim** [comment]
Okay, let me explain what we have for the takeoff speed computation in the MCDU. It is not doing a full takeoff performance analysis. The assumption is that you already know that the weight you are using to take off from the runway you are using in the wind/temperature/pressure conditions that exist is okay and that there are no obstacle or climb restrictions for which you may need a higher V2 speed. This means that V2 speed will simply be a function of the takeoff weight with a very slight variation with pressure altitude. We chose to use the V2 speeds at sea level, but they are only off by 1 knot up to about 8000 feet pressure altitude except at very light weights. Hence, for the stated assumption that any climb or obstacle limits are not considered, the V2 speeds are very realistic.

For VR and V1, we did simplify things a bit more and used a constant offset from V2. The chosen VR speed must allow the attainment of V2 by the time the airplane is 35 feet above the runway, so it depends on how fast the airplane is accelerating at that point. For CONF 1+F and CONF 2, the chosen offset of 4 knots works pretty well (within a knot or 2) at typical operating conditions. For CONF 3, being a little draggier, the difference between VR and V2 should probably be more like 1 or 2 knots.

For V1, since the takeoff is assumed not to be limited by the runway length (in fact,there is no runway length consideration include at all in this assumption), there are a range of possible V1 values that operators can choose from.  V1=VR is the highest; we simply chose VR-1. Since engine failure during takeoff is not modeled in the sim, you are free to choose a lower V1 to give yourself more safety margin to stop on the runway if you choose to reject a takeoff below V1.

Short summary:  Although there can be some very small refinement of the VR and V2 speeds, the ones currently in the MCDU are very close to the actual speeds for a takeoff not limited by climb or obstacle requirements. The V1 speed reflects the lack of any takeoff runway length performance analysis and the fact that engine failure during takeoff is not simulated. So, you are free to use any V1 speed up to where V1=VR. When some sort of takeoff runway analysis is added to the EFB, a more refined V1 will be given.

So, if you take off at about the same weight each time, you will get the same takeoff speeds regardless of where you are departing from (except above 5000 feet pressure altitude with CONF 3).
