### ISSUE TITLE
Terr on ND elevation values incorrect in ROSE mode

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8227]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-22T09:37:54+00:00",
    "ref": "refs/heads/master",
    "sha": "c31b180ef291f26252b57cfab9be92e98e256754",
    "actor": "mjuhe",
    "event_name": "manual",
    "pretty_release_name": "master:c31b180e",
    "version": "v0.11.0-dev.c31b180"
}
```

### Describe the bug

Minimum and maximum elevation values of terrain seem to be stuck at 000 and 001 regardless of the terrain situation when ROSE mode is selected on the ND.
![TERR](https://github.com/flybywiresim/aircraft/assets/119708186/b5c7c351-1fd9-46d1-8e0f-633545ca2c14)
![TERR2](https://github.com/flybywiresim/aircraft/assets/119708186/86770a72-1a0e-4a1e-b343-0ebcbac8b1d8)

### Expected behavior

Elevation values displayed on the ND should reflect the terrain situation.

### Steps to reproduce

1) Have simbridge running and turn on terr on ND
2) Switch between ROSE and ARC ND modes

### Additional info (optional)

At lower altitudes the issue is more obvious when there is terrain displayed as green or red, while the elevation remains green (001 & 000)

### Discord Username (optional)

bruno_pt99

**Comment by Maximilian-Reuter** [comment]
@Lucky38i This issue seems to be somewhere inside the Simbridge GPU code for the terrainmap.
The Pixel array that is returned from the GPU doesnt contain the metadata row in ROSE mode:
![image](https://github.com/flybywiresim/aircraft/assets/5833783/f0876790-2ecf-47e7-add8-dbad6856c6d4)

Maybe you or someone else more familiar than me with the terrain code can take a look

**Comment by svengcz** [comment]
Thanks, I will take a look
