### ISSUE TITLE
Ground Power works, even when the corresponding truck isn't present

### ISSUE THREAD

**Issue by Creative-Difficulty** [flybywiresim/aircraft#8284]
### Aircraft Version

Development

### Build info

```json
(currently on my macbook, will fill in later)
```

### Describe the bug

The External power button on the overhead panel says "AVAIL", even when there is no GPU present at the aircraft.

### Expected behavior

The External power button button only says AVAIL, when the GPU truck is called through either the FBW tablet, the MSFS ATC menu or the GSX menu.

### Steps to reproduce

1. Spawn in
2. Look up to the overhead panel
3. See that the External power button says AVAIL, even when no source of external power is present

### Discord Username (optional)

@immahead

**Comment by Benjozork** [comment]
A lot of gates have power built in, in msfs as well.

**Comment by tracernz** [comment]
This is intentional as there is no way to reliably know if a gate should have power or not (MSFS only knows about GPUs, not gate power) and it's better to have it than not.

**Comment by Creative-Difficulty** [comment]
Not in my opinion, as alternatively the plane can just be started via APU

**Comment by tracernz** [comment]
That would not be ideal when you're parked at a gate that is meant to provide power. You can simply use the APU instead of external power if you desire, but the opposite would not be possible if we took this away. A better solution would of course be for the sim to know about gate power but we can't control that.
