### ISSUE TITLE
GSX refueling truck issue

### ISSUE THREAD

**Issue by TTTTdayjunior** [flybywiresim/aircraft#8434]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-20T14:55:29+00:00",
    "ref": "refs/heads/master",
    "sha": "9f9e8313cab268c6414cfc3fe6db3c40c199a054",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:9f9e8313",
    "version": "v0.12.0-dev.9f9e831"
}
```

### Describe the bug

When the GSX payload and Fuel is synced, I call a fuel truck to reful as per simbrief loaded flight plan, by clicking the little cloud to load in the data, the fuel truck usually when starting the sim will arrive fuel and leave, however sometimes he will arrive start fueling and stop when not even 1/2 the requested amount is fueled, this from starting the sim happens very little, but it happens every time when doing a turn around. 

when doing a turn around he arrives, loads 1/4 or 1/2 at most fuel and leaves and I have to ask him to come fuel again and at which point he finishes the job. 

### Expected behavior

I except him to arrive fuel the expected amount and leave at the first time of asking.

### Steps to reproduce

During a turn around. 

Arrive,
Deboard,
Download new OFP and fuel and payload amounts. 
Request refuel via GSX 
Now because of an update if set to real he will start refueling on his own, and he will randomly stop and drive away.

### Discord Username (optional)

kris.novak

**Comment by Sleinmaster** [comment]
Was reported before as well, so I don't think that it's a new problem.

**Comment by Maximilian-Reuter** [comment]
yeah I think this has happened before

**Comment by alepouna** [comment]
Is this something caused by the integration or could it be just GSX? I can not reproduce this (for the record though I used slew mode to "approach" another airport)

**Comment by Sleinmaster** [comment]
I would say it's most likely a gsx bug, but hard to tell.

**Comment by Fragtality** [comment]
For me it sounds like Problems I saw with Fenix2GSX and these where related to the User's Setup. There is just one Point where SimConnect freaks out and Variables (GSX L-Vars) go arbitrary zero. And it does that because the Sim is one Way or the other "overloaded".
At least I could reproduce such a Behavior at will at any Time by setting FSDT_GSX_FUELHOSE_CONNECTED to 0 via my StreamDeck.

I've discussed that with @Maximilian-Reuter and took a look at the Code. There where some Calls setting the "User has requested Refuel" Variable back to false in the EFB Fuel Page I never really understood but left there - I mean someone somewhen must have seen a Purpose in that 😅 
They are not the Problem per-se, but contribute - because the User ends up with the Hose reported as not connected and Refuel not requested triggering the Refuel Process to stop.

So the quick-fix I'd propose is to just get rid of these two Calls, because I don't see any Purpose (but I might be just blind ^^). If GSX is still running, the Refuel Process just continues - Users in such Situations should not notice a Problem.
If GSX would crash it also continues. I don't see a Problem in that - the User has stated the Intent to Refuel. Why stopping it? Having the planned Fuel on Board is more important than the 3D-Model of a Fuel Truck I'd say ^^ And even if the User then decides to stop/finish Refuel because he/she does not want that without a Truck - PR #8407 allows to select Instant and the Process stops (with having the planned FOB).

At least that is my View as pessimistic and grumpy Developer that has seen too many Things with GSX 🤣

**Comment by Fragtality** [comment]
@TTTTdayjunior 
It would still require FBW's QA to test & approve it, but since you have that Problem very regularly: can you please also Test the proposed Fix/Workaround? (See "How to download the PR for QA" under https://github.com/flybywiresim/aircraft/pull/8437)

**Comment by TTTTdayjunior** [comment]
Interestingly seems that the version i had from the 24th of January, when landing and turning around refueled with the correct amount and he didn't leave halfway through.

this file youve asked me to test, he packed his things after 1 ton of fuel fueled and it carried on as you say, but interesting that it started to work fine after the version which I had prior to this...

**Comment by Fragtality** [comment]
Sorry, I can't follow.

When the GSX Animation still stops even while the Fuel is still increasing, it seems more and more like a Problem with your Setup/Sim to mw.
