### ISSUE TITLE
FCU: QFE text missing

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8478]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-02-09T12:00:46+00:00",
    "ref": "refs/heads/master",
    "sha": "49ee675cd43ab234e9b9adc04198c4bb4338dac2",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:49ee675c",
    "version": "a32nx-v0.12.0-dev.49ee675"
}
```

### Describe the bug

"QFE" text is missing on the FCU despite being visible on the PFD
![QFE](https://github.com/flybywiresim/aircraft/assets/119708186/87971a2e-1790-4a3c-a72c-b08bd9081f3e)
![QFE1](https://github.com/flybywiresim/aircraft/assets/119708186/4f4e34c8-e725-45b1-adc2-9260b957a0c8)

### Expected behavior

QFE text should be visible on the FCU since it is possible to toggle QFE.

### Steps to reproduce

Toggle QFE by left clicking the baro selector or perform the annunciator light test.

### References (optional)
![image](https://github.com/flybywiresim/aircraft/assets/119708186/e6e18a6c-89d5-43e6-a590-9f9e4b92c55d)

_No response_

### Additional info (optional)

IIRC it was visible on the old FCU/pre model update. 

### Discord Username (optional)

bruno_pt99

**Comment by tracernz** [comment]
We discussed removing the QFE option as most of the other systems actually don’t implement the QFE logic anyway.

**Comment by BravoMike99** [comment]
Alright, but the QFE text is always there on the baro selector even if the aircraft is not fitted with the QFE option (visible during ANN LT test) if not mistaken.

**Comment by BenJuan26** [comment]
I know what's happening, but I don't quite understand why (I'm a dev but I've never worked on a sim aircraft).

The pressure mode is grabbed here: https://github.com/flybywiresim/aircraft/blob/master/fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js#L1372

If everything worked correctly, it would only rely on the value of `L:XMLVAR_Baro1_Mode` and return either `QFE`, `QNH`, or `STD`. This is a special case for `Aircraft.A320_NEO`. For all other aircraft, the returned value is only ever `"STD"` or `""`, and it instead relies on `L:XMLVAR_Baro1_ForcedToSTD`. You might see where this is going.

If we accidentally tell `Simplane.getPressureSelectedMode()` that we're a CJ4, it will only tell us whether the pressure mode is `STD` or not. Let's see what happens if we get an empty string as our mode: https://github.com/flybywiresim/aircraft/blob/master/fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js#L1398-L1400

It will get stuck on `isQFE = false`. So, evidently, for some reason we're not telling that function that we're an A320_NEO, and it can only tell us whether we're in STD mode or not. QFE/QNH makes no difference.

Interestingly, doing a Quick Reload makes this problem go away. Why would the initial value of `Aircraft.A320_NEO` be unpopulated or incorrect, but set correctly on reload?
