### ISSUE TITLE
INIT Page: field 'FLT NBR' not populated by Simbrief, and cannot be entered manually

### ISSUE THREAD

**Issue by StephN-B** [flybywiresim/aircraft#8650]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-04-27T16:40:29+00:00",
    "ref": "refs/heads/master",
    "sha": "7518ab0c54b296f4cb774519889171ed7d8b4df5",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:7518ab0c",
    "version": "a32nx-v0.12.0-dev.7518ab0"
}
```

### Describe the bug

On the INIT page, the FLT NBR field is neither populated after initializing from a Simbrief plan, nor can it be manually entered.
Note that on the INIT/REVIEW page, the Flt Nbr is correct.

### Expected behavior

FLT NBR should be

1. populated as defined in the Simbrief flight plan
2. AND it should be possible to manually modify it

### Steps to reproduce

1. Create a Simbrief flight plan, e.g. EDDS to EHAM. Make sure to include an ATC Callsign (I used DLH2NB).
2. Start C/D on any stand in your departure airport
3. On the MCDU, go MCDU MENU > ATSU > AOC MENU > INIT/PRES
4. Click INIT DATA REQ -> all is OK. Note the correct Flight Number in the top left corner
5. Go to page INIT
6. Load the flight plan 
-> BUG 1: note that the FLT NBR remains empty 
7. Enter a flight number manually (e.g. DLH2NB) in the scratchpad, and then click the corresponding line key 
-> BUG 2: the value is not accepted, no error message displayed

### Discord Username (optional)

StephN-B

**Comment by 2hwk** [comment]
Should already be the case.

Note that this can occur if you have enabled the FBW API connection and someone else is already using your flight number, it will show FLT NUMBR IN USE.

**Comment by StephN-B** [comment]
Thanks @2hwk for your suggestion, but this isn't the cause of my issue. 
I made sure that only MSFS is running on my machine, and the issue persists as described above.
There also is NO message of FLT NUMBR IN USE.

**Comment by BenJuan26** [comment]
Does this happen for different flight numbers? Even flight numbers that wouldn't exist IRL? How about different origin and dest airports? I will try to reproduce but want to make sure any variables are accounted for.

**Comment by tracernz** [comment]
It's delayed because when you enter a flight number an async request goes off to the FBW API to "logon". That comes back either normal and then the flight number gets populated, or you get the FLT NBR IN USE. I don't know if there's anything to request an immediate redraw of the CDU page when the normal response comes back. I don't like the whole way it works personally; that's just not how the flight number field is supposed to work on an A320.

**Comment by BenJuan26** [comment]
I've done this about 20 times now with different time delays, systems running, and even flight numbers. I've never seen `FLT NBR IN USE`. This isn't redraw-related, because when it doesn't accept any input, navigating away from the page and back doesn't change anything. I would expect to see calls to the FBW API in Coherent's network tab, but, at least when I'm looking at `VCockpit08`, I don't see those calls. I see the health checks and the calls to SimBrief though.

If this is a matter of the flight number being in use, that's fine, but something in that flow is broken.

**Comment by tracernz** [comment]
Ah, the ATSU cannot send messages to the FMGC scratchpad (IRL and on the A32NX), so that might explain part of it. But the real ATSU does not send such a scratchpad message anyway.

**Comment by StephN-B** [comment]
I've just tested again using flight YPPH - YMML, using real life data for flight number, and the issue persists.
And given that Headwind Simulations are using your framework for their Airbus, I also tried the same with the Headwind A339X (Pre-Release v0.6-alpha.4), and the same is happening there. ... In case that helps.

But I'm glad you can recreate it - thanks for persisting ;-).

**Comment by milesy1188** [comment]
Hello, had exact same issue with FLT NBR not populating, for every single flight for the last 2-3 weeks. At the same time I was getting a ;Reverse Proxy Error; message as well. Someone mentioned the reverse proxy message was to do with Hoppie. So I went into the EFB, disabled Hoppie, and now the FLT NBR populates again perfectly every time. Worth trying to replicate with Hoppie disabled... I also don't know if it was because my Hoppie logon code had expired as well. I will try tomorrow to renable hoppie but with a new logon code and see if that also works.

**Comment by alepouna** [comment]
> Hello, had exact same issue with FLT NBR not populating, for every single flight for the last 2-3 weeks. At the same time I was getting a ;Reverse Proxy Error; message as well. Someone mentioned the reverse proxy message was to do with Hoppie. So I went into the EFB, disabled Hoppie, and now the FLT NBR populates again perfectly every time. Worth trying to replicate with Hoppie disabled... I also don't know if it was because my Hoppie logon code had expired as well. I will try tomorrow to renable hoppie but with a new logon code and see if that also works.

If your Hoppie logon code had expired, then that's why you got the Reverse Proxy Error.

**Comment by StephN-B** [comment]
With the above comment, I tried the following:

- Create and retrieve a new Hoppie's ACARS registration
- Start a flight CAD at EDDM
- In the EFB, copy in the new ACARS registration. 
- Leave ACARS as disabled (i.e. it was always disabled in my previous tests)
- Follow all steps as before -> FLT NBR is now populating 

**EXPECTED BEHAVIOUR**
- FLT NBR should populate regardless of Validity of ACARS registration, and also regardless of ACARS being enabled or disabled.

**Comment by ErikNL80** [comment]
To add on this, can you also prefill the flight number and altitude from a default MSFS plan when working on this???
