### ISSUE TITLE
Avast protects me from starting SimBridge

### ISSUE THREAD

**Issue by DePolle** [flybywiresim/aircraft#8652]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

Avast reports malware, Win64:Malware-gen, and quarantines the powershell page.

### Expected behavior

how to solve this problem

### Steps to reproduce

I'm not sure about turning off the firewall considering this maleware threat

### References (optional)

![FBW Avast](https://github.com/flybywiresim/aircraft/assets/38812081/08388570-0403-4afa-b4bf-0af09020d06d)

### Additional info (optional)

After update simbridge 0.5.3

**Comment by alepouna** [comment]
SimBridge, like other software, require dependencies in order to not re-invent the wheel for simple things. Unfortunately, some of these dependencies sometimes are used by malicious actors to create malware. As such, some anti-virus software flags any software that uses these common dependencies as malware, even though it really shouldn't. This includes SImbridge as well.

The best thing to do is update your antivirus database as it may have labeled Simbridge as safe since. Obviously I won't dictate how to handle the security of your computer, but if you feel that you can trust a big open-source organization that the application is safe, feel free to add an exception to your antivirus (and firewall potentially) for Simbridge, and it should work perfectly fine. 

The repository for Simbridge is also available here: https://github.com/flybywiresim/simbridge so you can alternatively, if you have some simple technical knowledge, review and audit the code and if you deem it safe you can also build Simbridge from the source.

**Comment by 2hwk** [comment]
https://github.com/flybywiresim/simbridge/issues 
Should be in this repository, closing.

**Comment by DePolle** [comment]
Thanks for your cooperation, but the technical information is too difficult for me.
I will wait for the next update of simbridge.
I have contacted Avast over the last 3 days to make an exception, but I have not received an answer.

**Comment by DePolle** [comment]
thanks for your cooperation, but the technical information is too difficult for me.
I will wait for the next update of simbridge.
I have contacted Avast over the last 3 days to make an exception, but I have not received an answer.

**Comment by DePolle** [comment]
After update 0.5.4 ok now.
