### ISSUE TITLE
bug: Old EFB repo Redirect link

### ISSUE THREAD

**Issue by Creative-Difficulty** [flybywiresim/aircraft#8787]
### Aircraft Version

Stable

### Build info

```json
N/A
```

### Describe the bug

N/A

### Expected behavior

Correct redirct to new EFB folder in aircraft repo.

### Steps to reproduce

1. Go to https://github.com/flybywiresim/efb
2. find the redirect link is broken (__even with github.com/ in front of it__)

### Additional info (optional)

Fix it by replacing the link with https://github.com/flybywiresim/aircraft/tree/master/fbw-a32nx/src/systems/instruments/src/EFB (the correct folder). __However, since the repo is archived, I can't open a PR there.__

### Discord Username (optional)
immahead

**Comment by Creative-Difficulty** [comment]
@BlueberryKing

**Comment by alepouna** [comment]
The EFB repository has been outdated for a while, and has been archived for quite some time as well. The link is generally completely invalid due to the repository rename anyways (from when we switched to monorepo) plus the EFB systems being under a common directory. That being said, the link doesn't redirect to something critical (and figuring out that the repo has changed, plus browsing it should get you back on track) 

While I don't think unarchiving just to fix the link is that needed, the team should however discuss if we should unpin it from the org
