### ISSUE TITLE
Thrust Lever Config Not Working

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/aircraft#8909]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

Calibrate the thrust levers with 2 independent axes. All works well in the EFB. Config seems to be ignored by the engines though, and axis 1 controls engine 1, axis 2 engine 2.

### Expected behavior

With 2 axes: Axis 1 controls engines 1 & 2, axis 2 controls engines 3 & 4.
With 1 axis: Axis 1 controls all 4 engines.

### Steps to reproduce

Calibrate the thrust levers with 2 independent axes.
Save and apply.
Move levers and look at EWD.
Try same with 1 axis.

**Comment by frankkopp** [comment]
To clarify:
The current implementation assumes that the user configures MSFS to map which axis controls which engine.
So if you configure MSFS so that your axis 1 controls engine throttle 1&2 and axis 2 controls axis 3&4 throttle calibration works as expected. 

If we want to avoid this we need to do this mapping in our UI and handle the mapping in the fbw wasm code. 
This UI does not yet exist and would have to be build as well (as some extra configs in the throttle calibration page?).
