### ISSUE TITLE
ZFW / GW switching - EFB tablet

### ISSUE THREAD

**Issue by marquinhosue** [flybywiresim/aircraft#9328]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Button to switch between GW and ZFW values does not work when view is setted to EFB Flypad, that is Ctrl + 0

### Expected behavior

Switch between GW and ZFW values should happend, as it is when a more far view is selected

### Steps to reproduce

1. Inititalize the plane
2. Switch to "ctrl+0" preset view
3. Try to press the swicthing button in EFB/Ground/Paylooad page

### References (optional)

None

### Additional info (optional)

None

### Discord Username (optional)

none

**Comment by LunakisDev** [comment]
I found out what is the problem. The problem is the window click spot behind the EFB, I played with the camera values and I can confirm that the problem is the click spot of the window. If you change the camera value to 1 cm higher the click spot works as you can see.

https://github.com/user-attachments/assets/62deca2f-76c6-495e-9540-bb42a83d32cf
