### ISSUE TITLE
Extreme Lattitude Alarm

### ISSUE THREAD

**Issue by AMM4R1NH0** [flybywiresim/aircraft#9329]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

![Capture d’écran (486)](https://github.com/user-attachments/assets/d693fd8a-cb6a-4c58-a9f6-f89d0ad15e29)
![Capture d’écran (487)](https://github.com/user-attachments/assets/c62bdff8-1931-46cb-bc19-950c32ddfd48)

Got the Extreme Lattitude
North Ref Sel ........ True

I don't where it comes from
The thing i know is i was flying over North Pole at the time of the appearance of the alarm

### Expected behavior

My plane went off flight path and won't go back

### Steps to reproduce

There is no steps to reproduce, just press Recall to see the msg again

### Discord Username (optional)

djazairi.213

**Comment by Maximilian-Reuter** [comment]
This isnt a bug but rather exactly what is supposed to happen. This ECAM tells you to switch your North Reference to TRUE instead of MAG. You can do that using the button located above the HDG window on the FCU.

Also for future reference, you put in the expected behavior section what you expect would happen on a working plane.
