### ISSUE TITLE
[A380X] Flight phase during G/A switches from 6 to 9/8 when reducing thrust

### ISSUE THREAD

**Issue by flogross89** [flybywiresim/aircraft#9354]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

When setting TOGA during a GA, flight phase switches to 9 correctly. However, when reducing the thrust to FLX/MCT or CLB shortly after, the flight phase switches to 8 and then 9 quickly while below 800ft.

When performing a GA due to ROW, this leads to ROW yelling "RWY TOO SHORT" if thrust reduction happens below 600ft AGL

### Expected behavior

To be checked with references, should remain in 6, then go to 7 and remain there until 1500ft AGL or 2min since lift-off I presume

### Steps to reproduce

see above

**Comment by flogross89** [comment]
If fixed, remember to remove `Tmpy hax until flight phase improve FIXME`

**Comment by BravoMike99** [comment]
On the A320 with its equivalent phases (5/Lift off and 7 800ft touchdown) this is expected behavior as the conditions for the phases are as follows:
< 1500FT && engines in takeoff power && not on ground -> phase 5
< 1500FT && <800FT && !engines in takeoff power && not on ground  -> phase 7
As a result, once the TLAs are no longer in FLX/MCT it can jump back to the landing phases which is probably what is happening here.
For the A380, there seems to be a FCOM note about this:
"In flight phase 7, if the thrust is reduced (thrust levers at CL), the flight phase changes
from 7 to 9. When the aircraft crosses 1 500 ft, the flight phase will then change from 9 to
8"
Interestingly enough they don't mention a jump from phase 6 to phase 9 but I assume its because in normal ops nobody will go to climb thrust below that 400ft and that's the minimum value accepted by the MFD anyways.

**Comment by flogross89** [comment]
> On the A320 with its equivalent phases (5/Lift off and 7 800ft touchdown) this is expected behavior as the conditions for the phases are as follows: < 1500FT && engines in takeoff power && not on ground -> phase 5 < 1500FT && <800FT && !engines in takeoff power && not on ground -> phase 7 As a result, once the TLAs are no longer in FLX/MCT it can jump back to the landing phases which is probably what is happening here. For the A380, there seems to be a FCOM note about this: "In flight phase 7, if the thrust is reduced (thrust levers at CL), the flight phase changes from 7 to 9. When the aircraft crosses 1 500 ft, the flight phase will then change from 9 to 8" Interestingly enough they don't mention a jump from phase 6 to phase 9 but I guess its because they assume in normal ops nobody will go to climb thrust below 400ft as that's the minimum value accepted by the MFD anyways.

Thanks for the insight! Then I'll add another condition in ROW/ROP to avoid this happening during G/A.
